name: aws_cloudwatch
description: An easy, lightweight, turnkey solution for logging with AWS CloudWatch
version: 1.0.1
homepage: https://github.com/Zsmerritt/Flutter_AWS_CloudWatch

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  aws_request:
    git:
      url: https://github.com/morenojulio/Flutter_AWS_Request.git
      ref: main # branch name
      publish_to: none
  synchronized: ^3.1.0 # Synchronize requests to ensure valid keys
  http: ^0.13.6 # Http package for parsing AWS responses correctly on Multiple Platforms
  crypto: ^3.0.3 # Message hashes used to collate split messages

dev_dependencies:
  test: ^1.24.0